package exception_handling;

public class Test {
    public static void main(String[] args) {
       try{
           //System.out.println(10/0);
           //return;
           //System.exit(0);
       }
       //catch(ArrayIndexOutOfBoundsException | ArithmeticException obj){
       //}
        finally{
           System.out.println("ok");
       }
        //System.out.println("End of the main");
    }
}
